image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu20.04:latest

stages:
  - build
  - static-analysis
  - pages

autoconf:
  stage: build
  script:
    - sh ci/gitlab-ci autoconf
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

autoconf-library-only:
  stage: build
  script:
    - sh ci/gitlab-ci autoconf
      --disable-tiff-tools --disable-tiff-contrib --disable-tiff-man
      --disable-tiff-html --disable-tiff-tests
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

cmake-makefiles:
  stage: build
  script:
    - sh ci/gitlab-ci cmake "Unix Makefiles" Release

cmake-ninja:
  stage: build
  script:
    - sh ci/gitlab-ci cmake "Ninja" Debug

cmake-library-only:
  stage: build
  script:
    - sh ci/gitlab-ci cmake "Ninja" Release
      -DLIBTIFF_BUILD_TOOLS=OFF -DLIBTIFF_BUILD_CONTRIB=OFF
      -DLIBTIFF_BUILD_MAN=OFF -DLIBTIFF_BUILD_HTML=OFF

cmake-ninja-arm64:
  tags: [arm64,freebsd]
  stage: build
  script:
    - sh ci/gitlab-ci cmake "Ninja" Release
  rules:
    - if: '$CI_PROJECT_PATH == "libtiff/libtiff"'

coverity:
  stage: static-analysis
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu20.04-coverity:latest
  script:
    - sh ci/gitlab-ci coverity "Ninja" Debug
  only:
    refs:
      - master

pages:
  stage: pages
  script:
    - cp -r html public
  artifacts:
    name: $CI_PROJECT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
  - master
