image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu12.04:latest

stages:
  - static-analysis
  - build
  - pages

autoconf:
  stage: build
  script:
    - sh build/gitlab-ci autoconf
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

cmake-makefiles:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

cmake-ninja:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug

coverity:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PROJECT_NAMESPACE != "libtiff"'
      when: never
    - when: always
  stage: static-analysis
  script:
    - sh build/gitlab-ci coverity "Ninja" Debug

pages:
  stage: pages
  script:
    - cp -r html public
  artifacts:
    name: $CI_PROJECT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
  - master
